language: node_js
sudo: true
dist: trusty
cache:
  directories:
    - $HOME/.npm
    - node_modules
    - packages/core/node_modules
    - packages/crud/node_modules
    - packages/form/node_modules
    - packages/site/node_modules
node_js:
  - "8"

before_install:
  - "export CHROME_BIN=/usr/bin/google-chrome"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN"
  - "git remote add source https://${GH_TOKEN}@github.com/ngx-rapid/ngx-rapid.git"
  - "git remote add ghpage https://${GH_TOKEN}@github.com/ngx-rapid/ngx-rapid.github.io.git"

install:
  - npm install

script:
- export REPO_VERSION=`node -pe "require('./lerna.json').version"`-$TRAVIS_BUILD_NUMBER
- npm run version:ci
- npm run lint
- npm run test
- npm run build

after_success:
  - bash <(curl -s https://codecov.io/bash)
#  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run publish:git
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run publish:npm
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run publish:site

branches:
  only:
  - master

addons:
  apt:
    packages:
      - google-chrome-stable
